packages:
  - apps/*
  - packages/*

catalog:
  # React ecosystem
  'react': '19.0.0'
  'react-dom': '19.0.0'
  '@types/react': '~19.0.10'
  '@types/react-dom': '^19.0.4'

  # TanStack ecosystem
  '@tanstack/react-form': '^1.15.2'
  '@tanstack/react-query': '^5.84.1'
  '@tanstack/react-router': '^1.130.12'
  '@tanstack/react-router-with-query': '^1.130.12'
  '@tanstack/react-start': '^1.130.12'
  '@tanstack/router-plugin': '^1.130.12'
  '@tanstack/react-router-devtools': '^1.130.12'

  # Backend & Database
  'convex': '^1.25.4'
  '@convex-dev/react-query': '^0.0.0-alpha.8'

  # Build tools & TypeScript
  'typescript': '~5.8.2'
  'vite': '^7.0.6'
  '@vitejs/plugin-react': '^4.5.2'
  '@vitejs/plugin-react-swc': '^3.5.0'

  # UI & Styling
  'tailwindcss': '^4.1.3'
  '@tailwindcss/vite': '^4.1.8'
  'class-variance-authority': '^0.7.1'
  'clsx': '^2.1.1'
  'tailwind-merge': '^3.3.1'
  'lucide-react': '^0.525.0'
  'next-themes': '^0.4.6'
  'sonner': '^2.0.3'
  'tw-animate-css': '^1.2.5'

  # Utilities
  'zod': '^3.22.4'
  'vite-tsconfig-paths': '^5.1.4'

  # Testing
  '@testing-library/dom': '^10.4.0'
  '@testing-library/react': '^16.2.0'
  'jsdom': '^26.0.0'
  'web-vitals': '^5.0.3'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - nx
